### ISSUE TITLE
Create function [data_download]

### ISSUE THREAD

**Issue by soriadelva** [inbo/ClimateCastR#19]
## data_download
Function to download data from GBIF, with the same functionality as is currently implemented in climate_match.R but with addition of

- [x] the possibility to use download key from a gbif download to import species occurrence data (#4)
- [x] BasisOfRecord: use the same rationale to filter these data as is already present in trias (coordinatecleaner) (#11)
- [x]  IdentificationVerificationStatus: to_discard <- c( "unverified", "unvalidated","not able to validate", "control could not be conclusive due to insufficient knowledge") see (https://github.com/trias-project/occ-cube/blob/main/src/2_create_db.Rmd) (#11)

The output of this function is a dataset (currently this dataset was exported as 'spatial' by the climate_match () function).

## Checklist
- [x] maak een nieuw R-bestand 
- [x] sla het R bestand op onder `./R` met filenaam is gelijk aan functienaam
- [x] voorzie een functie titel met `#'` op regel 1 van je script
- [x] voorzie een auteur met `#' @author`
- [x] voorzie een beschrijving met `#' @description`
- [x] voorzie uitleg over de input parameter(s) met `#' @param name`
- [x] voorzie uitleg over de output van de functie met `#' @returns`
- [x] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [x] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [x] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [x] voer `roxygen2::roxygenise()` uit in de console
- [x] voer `devtools::check()` uit in de console
- [x] los eventuele errors, warnings en notes<sup>1</sup> op
- [x] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*
