### ISSUE TITLE
Create function [plot_single_species]

### ISSUE THREAD

**Issue by soriadelva** [inbo/ClimateCastR#25]
## Voorstel functie naam
Create a list of leaflet maps (one for each species), showing the climate matching for each future scenario of interest (selected in the menu). These maps are created by linking the data in the unfiltered dataset (created by the climate_match() function) to the world map of the Köppen-Geiger climate classification for each future scenario.

Additional things to take into account:
- [ ]  Plot the region outline on top of the map (see https://github.com/inbo/ClimateCastR/issues/16)
- [ ] Don't plot the occurrence records on top of the map by default (see https://github.com/inbo/ClimateCastR/issues/10)
- [ ] When the user defines a region in the function, the leaflet maps should be immediately zoomed in on this region. (https://github.com/inbo/ClimateCastR/issues/9)

## Checklist
- [ ] maak een nieuw R-bestand 
- [ ] sla het R bestand op onder `./R` met filenaam is gelijk aan functienaam
- [ ] voorzie een functie titel met `#'` op regel 1 van je script
- [ ] voorzie een auteur met `#' @author`
- [ ] voorzie een beschrijving met `#' @description`
- [ ] voorzie uitleg over de input parameter(s) met `#' @param name`
- [ ] voorzie uitleg over de output van de functie met `#' @returns`
- [ ] voorzie minstens 1 voorbeeld van het gebruik van de functie dmv `#' @examples`
- [ ] voorzie de export - tag dmv `#' @export` ([#14](https://github.com/inbo/fistools/issues/14))
- [ ] voer `usethis::use_package("packagename", min_version = TRUE)` uit in de console voor iedere package die je gebruikt. 
- [ ] voer `roxygen2::roxygenise()` uit in de console
- [ ] voer `devtools::check()` uit in de console
- [ ] los eventuele errors, warnings en notes<sup>1</sup> op
- [ ] maak een pull request met @soriadelva of @SanderDevisscher en eventueel andere relevante gebruikers als reviewer.

*<sup>1</sup>in de mate van het mogelijke*
